modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/HridayKh/MoreGenerators/issues"

[[mods]]

modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL = "https://github.com/HridayKh/MoreGenerators/"
logoFile = "logo.png"
credits = "HridayKh.in"
authors = "HridayKh.in"
description = '''
Adding more Electricity Generators to a world near you!
'''

[[dependencies]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies]]
modId = "powergrid"
type = "required"
versionRange = "[0.5.5.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies]]
modId = "create"
type = "required"
versionRange = "[6.0.10,6.1.0)"
ordering = "NONE"
side = "BOTH"

[[dependencies]]
modId = "${mod_id}"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "AFTER"
side = "BOTH"

[[dependencies]]
modId = "${mod_id}"
mandatory = true
versionRange = "[${neo_version},)"
ordering = "AFTER"
side = "BOTH"
